DEFINES+=PROJECT_CONF_H=\"project-conf.h\"
CONTIKI_PROJECT = ade_test

TARGETDIRS += ../../platform

UIP_CONF_IPV6=1

all: $(CONTIKI_PROJECT)

CONTIKI = ../../../../contiki
include $(CONTIKI)/Makefile.include
